name: CI Quality Gates & Build Optimization

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------------------------------------------
  # Job 1: Code Quality & Automated Testing Gates
  # -------------------------------------------------------------
  quality-gate:
    name: Lint, Test & Coverage Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' # actions/cache: Dependency Caching doing super fast build

      - name: Install Dependencies
        run: npm ci

      # Gate 1: Code Style Enforcement
      - name: Run ESLint
        run: npm run lint

      # Gate 2: Automated Unit Tests + 80% Coverage Gate
      - name: Run Unit Tests & Check Coverage
        run: npm test

      # Test Reports (Artifact)
      - name: Upload Test Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  # -------------------------------------------------------------
  # Job 2: Optimized Docker Build with Layer Caching
  # -------------------------------------------------------------
  docker-build:
    name: Optimized Multi-Stage Docker Build
    needs: [quality-gate]  # Without passing quality-gate, build will not be create.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # GitHub Actions Cache use for Docker Layer Cache
      - name: Build Docker Image with Layer Caching
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # For local test
          tags: cloudpulse-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max